name: migu-sign

on:
  push:
  pull_request:
  schedule:
    - cron: 0 0/1 * * *

jobs:
  migu-sign:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup-python
      uses: actions/setup-python@master
      with:
        python-version: 3.7

    - name: requirements
      run: |
        pip3 install requests

    - name: sign
      env:
        COOKIE: ${{ secrets.COOKIE }}
      run: |
        python3 main.py